### ISSUE TITLE
Channels vagrant deploys, but alerts not working

### ISSUE THREAD

**Issue by senoadiw** [abarto/tracker_project#1]
Hi,

I managed to get a vagrant up from the channels branch, but unable to receive any alerts for incidents. Here is what I did to test it, please advise if anything is wrong:
1. I created a new superuser to login since I don't know the password for the existing users
2. Access the site at localhost:8000 (using Firefox 44.0.2 on Win 7)
3. Login with user from step 1
4. Draw a new area of interest at http://localhost:8000/tracker/area_of_interest/create/ with a severity of medium
5. Open http://localhost:8000 in browser window 2 and zoom in to the area of interest
6. In browser window 1 create an incident within the area of interest with medium severity
7. Expect a alert to popup in browser window 2 => no alerts
8. Refresh browser window 2 and there is a marker within the area of interest but no alerts

Is there any step that I am missing?

Cheers,

SN

**Comment by abarto** [comment]
It seems there's a problem with uWSGI (it works just fine with the development server). I'm looking into it right now.

**Comment by abarto** [comment]
As I suspected, channels 0.8 didn't have the code to adapt wsgi to asgi. I fooled around with the latest version of channels, asgi_redis and asgiref and everything seems to be working (no obvious errors) but messages aren't send through the WebSockets. I'll try with newer versions as soon as they're available, and I'll update this project accordingly.

**Comment by senoadiw** [comment]
Thanks for looking into this. Meanwhile I also tried the master branch vagrant and it works fine. As someone who is just getting into websockets, which of the tracker_project branches would you suggest to work with? Would the conclusions mentioned in the gevent-socketio blog post be an issue? The node_js approach seems more common but I have yet to try it.

Cheers,

SN

**Comment by abarto** [comment]
I would personally go with the Node.js branch as gevent-socketio seems to have been abandoned.

**Comment by abarto** [comment]
I've updated the code to work with the latest channel code. Everything should work now.

**Comment by senoadiw** [comment]
Thanks, I'll check it out!

**Comment by senoadiw** [comment]
Update: Just tested using the Vagrantfile, I can confirm that the incident alerts work again. Much appreciated.

Cheers,

SN

**Comment by senoadiw** [comment]
Update 2: There seems to be an issue where alerts stop appearing after a while. I keep the Incidents and Areas of Interest page open in one window and keep creating new incidents in another one. Alerts stop appearing by the 4th incident. Here is the last output from the console log (same on Firefox 44 and Chromium 49):

```
close close { target: WebSocket, isTrusted: true, wasClean: false, code: 1006, reason: "", currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1456896973372000 }
```

Cheers,

SN

**Comment by abarto** [comment]
I've implemented a simple connection try mechanism and a connection status label on the home interface.

**Comment by senoadiw** [comment]
It looks like there is a moment when the map stops showing alerts (with connection still green) and then the socket.onclose event is triggered which reconnects (and alerts start showing) until it repeats again.
